### ISSUE TITLE
Wordpress 3.2.0 released

### ISSUE THREAD

**Issue by alculete** [snapcrafters/wordpress-desktop#4]
There is a new release for wordpress version 3.2.0

**Comment by popey** [comment]
Awesome, thanks. I have tweaked the yaml so it should [build](https://launchpad.net/~build.snapcraft.io/+snap/ae0fd841540e3d1d06d98f3237a8d1ec-xenial) in edge shortly. If you get a moment, please `snap refresh wordpress-desktop --edge` and you will get the new build (once it's done).  Let us know and we can promote that to stable. Thanks!

**Comment by popey** [comment]
It finished building, and I tested it myself, so pushing to stable, thanks again!

**Comment by alculete** [comment]
Thank you... unfortunately I'm at work on Windows. I only can test at home
