### ISSUE TITLE
Wordpress lost its icon after update

### ISSUE THREAD

**Issue by alculete** [snapcrafters/wordpress-desktop#7]
WordPress lost its icon after update to  3.4.0

![image](https://user-images.githubusercontent.com/2129497/44631740-aeddc180-a970-11e8-8720-19597280eb0e.png)

**Comment by popey** [comment]
Confirmed. Not sure what's going on there, the desktop file looks wrong and may need manipulation in the build.

**Comment by popey** [comment]
Looks okay now.
